### PR TITLE
Added dependency package -> exec

### PR DESCRIPTION
**Pull request by gehel**
We need to ensure that the keyboard-configuration package is installed before we try to reconfigured it. I also changed the name of the exec resource from apply to apply-keyboard-configuration to reduce the risk of collision.

### CODE REVIEW

**Comment by nervo** [comment]
Well, there's already such a dependency check line 9 : https://github.com/nervo/puppet_keyboard/blob/master/manifests/init.pp#L9-L11
It does not work like it should ?

**Comment by gehel** [comment]
I might be blind (would not be the first time), but I see the package declaration on line 9, nothing ensures it is applied before the exec (yes I am still on Puppet 2.7). And when I try to apply this module, yes, the exec resource is applied before the package is installed ...

**Comment by nervo** [comment]
Hmmm, good point :+1: 

Let's do it, dude !

**Comment by nervo** [comment]
Damned, it seems things have changed in puppet forge...
Any tip to update to release 0.0.2 ?

**Comment by gehel** [comment]
no idea, never pushed a module to the forge (yet)

**Pull request merged**
